name: 'Kore apply'
description: 'Manage Kore infra based on github repo'
author: Chris Nesbitt-Smith
branding:
  icon: arrow-right-circle

inputs:
  kore-token:
    description: 'Kore robot token'
    required: true
  kore-team:
    description: 'The team to use in kore'
    required: true
  kore-server:
    description: 'Address of the kore server'
    required: true
  github-token:
    description: github token to use to pull the docker image secrets.GITHUB_TOKEN is probably fine
    required: true
  github-actor:
    description: github actor to use to pull the docker image github.actor is probably fine
    required: true
runs:
  using: 'composite'
  steps:
    - name: Login to docker.pkg.github.com
      shell: bash
      run: echo ${PASSWORD} | docker login --username ${USERNAME} --password-stdin ghcr.io
      env:
        USERNAME: ${{ inputs.github-actor }}
        PASSWORD: ${{ inputs.github-token }}
    - name: Run
      run: |
        docker run --rm \
        -e KORE_SERVER="$KORE_SERVER" \
        -e KORE_TEAM="$KORE_TEAM" \
        -e KORE_TOKEN="$KORE_TOKEN" \
        -v `pwd`:/workspace \
        -w /workspace \
        ghcr.io/appvia/kore-github-action:latest
      shell: bash
      env:
        KORE_SERVER: ${{ inputs.kore-server }}
        KORE_TEAM: ${{ inputs.kore-team }}
        KORE_TOKEN: ${{ inputs.kore-token }}
