apiVersion: policy.appvia.io/v1alpha1
kind: PolicyPlan
metadata:
  annotations:
    policies.appvia.io/category: role
  name: ci.admin
  namespace: ws-admin
spec:
  description: |
    Provides the capability to do anything in Kore
  policy:
    decision:
      action: allow
      message: Allow the subject to provision infrastructure
  selectors:
    - subject:
        scopes:
          - wayfinder:system:robot
    - resource:
        groups:
          - '*'
        resources:
          - '*'
        verbs:
          - '*'
