name: ci

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - id: docker_meta
        uses: docker/metadata-action@v3.3.0
        with:
          images: docker.pkg.github.com/appvia/kore-github-action/kore-github-action
          tag-sha: true
          tag-latest: true
          tag-semver: |
            {{version}}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Login to docker registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1.10.0
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2.5.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
